# Generated by Django 4.1.7 on 2024-01-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_user_work_type_worktype_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkType',
            new_name='Worker',
        ),
    ]
