# Generated by Django 4.1.7 on 2024-01-10 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=255)),
                ('service_price', models.IntegerField(blank=True, default=0, null=True)),
                ('total_completed', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(blank=True, default=1, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obyekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
                ('deal_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('given_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('real_dept', models.IntegerField(blank=True, default=0, null=True)),
                ('max_dept', models.IntegerField(blank=True, default=100000000, null=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_amount', models.ManyToManyField(to='obyekt_app.workamount')),
            ],
        ),
    ]
