# Generated by Django 4.1.7 on 2024-01-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyekt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obyekt',
            name='contract',
            field=models.FileField(default=1, upload_to='contracts/'),
            preserve_default=False,
        ),
    ]
