# Generated by Django 4.1.7 on 2024-01-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyekt_app', '0002_obyekt_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='obyekt',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
