# Generated by Django 4.1.7 on 2024-01-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyekt_app', '0004_alter_obyekt_work_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obyekt',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='obyekt',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AlterField(
            model_name='obyekt',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='obyekt',
            name='job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='obyekt',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
