# Generated by Django 4.1.7 on 2024-01-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyekt_app', '0005_alter_obyekt_address_alter_obyekt_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obyekt',
            name='work_amount',
            field=models.ManyToManyField(blank=True, to='obyekt_app.workamount'),
        ),
    ]
