# Generated by Django 4.1.7 on 2024-01-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyekt_app', '0007_obyektjobtype_workamountjobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='workamount',
            name='first_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
