# Generated by Django 4.1.7 on 2024-01-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyekt_app', '0008_workamount_first_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='workamount',
            name='visible_obyekt',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
