# Generated by Django 4.1.7 on 2024-01-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyekt_app', '0011_allow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to='instructsiya/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
