# Generated by Django 4.1.7 on 2024-01-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyekt_app', '0012_instructsiya'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructsiya',
            name='name',
            field=models.CharField(default='Instruktsiya', max_length=255),
        ),
    ]
