# Generated by Django 4.1.7 on 2024-01-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyekt_app', '0013_instructsiya_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obyekt_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to='obyekt_doc/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instructsiya',
            name='name',
        ),
    ]
