# Generated by Django 4.1.7 on 2024-01-31 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obyekt_app', '0014_obyekt_doc_remove_instructsiya_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='obyekt_doc',
            name='obyekt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obyekt_app.obyekt'),
            preserve_default=False,
        ),
    ]
