# Generated by Django 4.1.7 on 2024-02-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishchi_app', '0005_alter_workdaymoney_work_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='month',
        ),
        migrations.RemoveField(
            model_name='money',
            name='year',
        ),
    ]
