# Generated by Django 4.1.7 on 2024-02-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishchi_app', '0007_remove_money_total_earn'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='month',
            field=models.IntegerField(default=24290),
        ),
    ]
