# Generated by Django 4.1.7 on 2024-01-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('profit_percentage', models.IntegerField(default=0)),
                ('remain', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductHistorySoldOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokon_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokon_app.producttype'),
        ),
        migrations.CreateModel(
            name='HistorySoldOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_sold_out', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('history_products', models.ManyToManyField(to='dokon_app.producthistorysoldout')),
            ],
        ),
    ]
