# Generated by Django 4.1.7 on 2024-01-10 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obyekt_app', '0002_obyekt_contract'),
        ('dokon_app', '0003_producthistorycame_historycame'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_given', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('total_given_amount', models.IntegerField(default=0)),
                ('remain_amount', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('history_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obyekt_app.obyekt')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHistoryObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokon_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('history_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokon_app.historyobject')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='historyobject',
            name='history_products',
            field=models.ManyToManyField(to='dokon_app.producthistoryobject'),
        ),
        migrations.AddField(
            model_name='historyobject',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
