# Generated by Django 4.1.7 on 2024-01-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokon_app', '0006_remove_dokonday_date_alter_dokonday_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_type',
            field=models.CharField(blank=True, choices=[('elektr', 'Elektga oid'), ('santexnika', 'Santexnikaga oid')], default='elektr', max_length=50, null=True),
        ),
    ]
