# Generated by Django 4.1.7 on 2024-01-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokon_app', '0007_product_first_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='first_type',
        ),
        migrations.AddField(
            model_name='producttype',
            name='first_type',
            field=models.CharField(blank=True, choices=[('elektr', 'Elektga oid'), ('santexnika', 'Santexnikaga oid')], default='elektr', max_length=50, null=True),
        ),
    ]
