# Generated by Django 4.1.7 on 2024-01-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokon_app', '0008_remove_product_first_type_producttype_first_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DokonDay',
        ),
    ]
